{% set name = "logfury" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/logfury-{{ version }}.tar.gz
  sha256: 130a5daceab9ad534924252ddf70482aa2c96662b3a3825a7d30981d03b76a26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm <6.0
  run:
    - python >={{ python_min }}

test:
  imports:
    - logfury
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/reef-technologies/logfury
  summary: ('Toolkit for responsible, low-boilerplate logging of library method calls',)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - freundTech
